import assert from "node:assert/strict"
import test from "node:test"

import { createDiscordLinkToken, verifyDiscordLinkToken } from "../src/lib/discord-link-token.mjs"
import { decideDiscordLinkWrite } from "../src/lib/discord-link-ownership.mjs"
import { getPostLoginDestination, getSafeNextPath } from "../src/lib/safe-navigation.mjs"
import { createDiscordLinkToken as createBotLinkToken } from "../../discord-bot/src/lib/linkToken.js"

const secret = "test-only-secret-with-at-least-32-bytes"
const now = Date.UTC(2026, 6, 21, 12, 0, 0)

test("Discord link tokens prove the signed Discord identity", () => {
  const token = createDiscordLinkToken(
    { discordUserId: "123456789012345678", discordName: "mezzy" },
    secret,
    { now, ttlSeconds: 300 },
  )
  assert.deepEqual(verifyDiscordLinkToken(token, secret, { now: now + 60_000 }), {
    discordUserId: "123456789012345678",
    discordName: "mezzy",
    expiresAt: Math.floor(now / 1000) + 300,
  })
  assert.throws(() => verifyDiscordLinkToken(`${token.slice(0, -1)}x`, secret, { now }), /Invalid/)
  assert.throws(() => verifyDiscordLinkToken(token, secret, { now: now + 301_000 }), /expired/)
  assert.throws(() => createDiscordLinkToken({ discordUserId: "12345" }, "weak", { now }), /32 bytes/)
})

test("the web verifier accepts tokens generated by the Discord bot", () => {
  const token = createBotLinkToken(
    { discordUserId: "123456789012345678", discordName: "mezzy" },
    secret,
    { now, ttlSeconds: 300 },
  )
  assert.equal(verifyDiscordLinkToken(token, secret, { now }).discordUserId, "123456789012345678")
})

test("Discord links cannot be claimed or silently replaced", () => {
  assert.deepEqual(
    decideDiscordLinkWrite({
      discordLink: { hikari_user_id: "owner-a" },
      hikariLink: null,
      hikariUserId: "attacker-b",
      discordUserId: "12345",
    }),
    { ok: false, status: 409, reason: "discord_claimed" },
  )
  assert.deepEqual(
    decideDiscordLinkWrite({
      discordLink: null,
      hikariLink: { discord_user_id: "67890" },
      hikariUserId: "owner-a",
      discordUserId: "12345",
    }),
    { ok: false, status: 409, reason: "hikari_already_linked" },
  )
})

test("safe next redirects preserve internal context and reject external targets", () => {
  assert.equal(getSafeNextPath("/search?query=one%20piece&type=anime#results"), "/search?query=one%20piece&type=anime#results")
  assert.equal(getSafeNextPath("/media/21?action=favorite"), "/media/21?action=favorite")
  for (const unsafe of ["https://evil.example", "//evil.example/path", "/\\evil.example", "javascript:alert(1)"]) {
    assert.equal(getSafeNextPath(unsafe), "/")
  }
})

test("signed-in navigation resumes the requested page or carries it through onboarding", () => {
  const requested = "/media/21-one-piece?action=list"
  assert.equal(getPostLoginDestination(requested), requested)
  assert.equal(
    getPostLoginDestination(requested, { requiresOnboarding: true }),
    "/onboarding?next=%2Fmedia%2F21-one-piece%3Faction%3Dlist",
  )
  assert.equal(getPostLoginDestination("https://evil.example/steal"), "/")
})
